version: '2.1'
services:
  courses-api:
    container_name: horum_course-api
    build: ./courses-api
    volumes:
      - './courses-api:/usr/src'
      - './courses-api/package.json:/usr/src/package.json'
    ports:
      - '3000:3000'
    environment:
      - YANDEX_API=${YANDEX_API}
      - PORT=3000
      - DB_CONNECT_DEV=${DB_CONNECT_DEV}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      courses-db:
        condition: service_healthy
    links:
      - courses-db
  courses-db:
    container_name: horum_course-db
    build: ./db
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: exit 0